using RTTIScanner.ClassExtensions;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace __cxxabiv1
{
	/**
	  *  @brief  Part of RTTI.
	  *
	  *  The @c type_info class describes type information generated by
	  *  an implementation.
	 */
	public class type_info
	{
		public string name { get; set; }

		[Obsolete("TODO: GCC __cxa_demangle", true)]
		public static string __cxa_demangle(string str)
		{
			return null;
		}

		public static string demangle(string str)
		{
			return new Regex(@"^\d+").Replace(str, "");
		}
	}

	// Helper class for __vmi_class_type.
	public class __base_class_type_info
	{
		public IntPtr address { get; set; }
		public long offset_flags { get; set; }
	}

	// Type information for a class.
	public class __class_type_info : type_info
	{
		public __base_class_type_info currentObj { get; protected set; }
		public __class_type_info(IntPtr objAddress)
		{
			currentObj = new();
			currentObj.address = objAddress;
		}
	}

	// Type information for a class with a single non-virtual base.
	public class __si_class_type_info : __class_type_info
	{
		public __base_class_type_info baseClassInfo { get; set; }
		public __si_class_type_info(IntPtr objAddress) : base(objAddress)
		{
			baseClassInfo = new();
		}
	}

	// Type information for a class with multiple and/or virtual bases.
	public class __vmi_class_type_info : __class_type_info
	{
		public uint flags { get; set; }
		public uint base_count { get; set; }
		public __base_class_type_info[] arrBaseClassAddress { get; set; }
		public __vmi_class_type_info(IntPtr objAddress) : base(objAddress) { }
	}
}

namespace RTTIScanner.RTTI
{
	public class GCC : Parser
	{
		private static readonly Dictionary<string, Type> typeMapping = new Dictionary<string, Type>
		{
			// i dont care
			// { "St9type_info", typeof(__cxxabiv1.type_info) }, 
			{ "N10__cxxabiv117__class_type_infoE", typeof(__cxxabiv1.__class_type_info) },
			{ "N10__cxxabiv120__si_class_type_infoE", typeof(__cxxabiv1.__si_class_type_info) },
			{ "N10__cxxabiv121__vmi_class_type_infoE", typeof(__cxxabiv1.__vmi_class_type_info) }
		};

		private async Task<__cxxabiv1.type_info> CreateType(IntPtr pTypeInfo)
		{
			IntPtr classTypeInfo = await ReadRemoteIntPtr(pTypeInfo);
			string classTypeName = await ReadRemoteString(await ReadRemoteIntPtr(classTypeInfo - 32));

			if (!typeMapping.TryGetValue(classTypeName, out Type type))
			{
				throw new Exception("Failed to get typeinfo.");
			}

			__cxxabiv1.type_info instance = (__cxxabiv1.type_info)Activator.CreateInstance(type, new object[] { pTypeInfo });
			if (instance == null)
			{
				throw new Exception("Failed to CreateInstance on CreateType.");
			}

			return instance;
		}

		public override async Task<string[]> ReadRemoteRuntimeTypeInformation64(IntPtr startTypeInfo)
		{
			if (!startTypeInfo.IsValid())
			{
				return null;
			}

			return await base.ReadRemoteRuntimeTypeInformation64(startTypeInfo);

			IntPtr pCurrentAddr = startTypeInfo;



			// TODO: Full RTTI
			//return new string[] { typeName };
		}

		private async Task<__cxxabiv1.type_info> GetRTTIByTypeinfo(IntPtr pTypeinfo)
		{
			IntPtr pCurrentAddr = pTypeinfo;
			__cxxabiv1.type_info currentObj = await CreateType(pCurrentAddr);
			if (currentObj is __cxxabiv1.type_info info)
			{
				info.name = await GetTypeName(pCurrentAddr);
			}

			if (currentObj is __cxxabiv1.__class_type_info baseClass)
			{
				pCurrentAddr += 16;
			}

			if (currentObj is __cxxabiv1.__si_class_type_info si)
			{
				si.baseClassInfo.address = await ReadRemoteIntPtr(pCurrentAddr);
			}
			else if (currentObj is __cxxabiv1.__vmi_class_type_info vmi)
			{
				vmi.flags = await ReadRemote<uint>(pCurrentAddr);
				pCurrentAddr += 4;

				vmi.base_count = await ReadRemote<uint>(pCurrentAddr);
				pCurrentAddr += 4;

				vmi.arrBaseClassAddress = new __cxxabiv1.__base_class_type_info[vmi.base_count];
				for (int i = 0; i < vmi.base_count; i++)
				{
					vmi.arrBaseClassAddress[i] = new __cxxabiv1.__base_class_type_info();

					vmi.arrBaseClassAddress[i].address = await ReadRemoteIntPtr(pCurrentAddr);
					pCurrentAddr += 8;

					vmi.arrBaseClassAddress[i].offset_flags = await ReadRemote<long>(pCurrentAddr);
					pCurrentAddr += 8;
				}
			}

			return currentObj;
		}

		private async Task<string> GetTypeName(IntPtr pTypeinfo)
		{
			return __cxxabiv1.type_info.demangle(await ReadRemoteString(await ReadRemoteIntPtr(pTypeinfo + 8)));
		}
	}
}
